# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyLocation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('assembly_location', models.CharField(max_length=20, verbose_name='Assembly Location')),
            ],
            options={
                'verbose_name': 'Assembly Location',
                'verbose_name_plural': 'Assembly Locations',
                'permissions': (('browse_assemblylocation', 'Can browse Assembly Location'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AssemblyStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('assembly_status', models.CharField(max_length=20, verbose_name='Assembly Status')),
            ],
            options={
                'verbose_name': 'Assembly Status',
                'verbose_name_plural': 'Assembly Statuses',
                'permissions': (('browse_assemblystatus', 'Can browse Assembly Status'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BPManufacturer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bp_manufacturer', models.CharField(max_length=30, verbose_name='BFP Manufacturer')),
            ],
            options={
                'verbose_name': 'BFP Manufacturer',
                'verbose_name_plural': 'BFP Manufacturers',
                'permissions': (('browse_bpmanufacturer', 'Can browse BP Manufacturer'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BPSize',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bp_size', models.CharField(max_length=10, verbose_name='BFP Size')),
            ],
            options={
                'verbose_name': 'BFP Size',
                'verbose_name_plural': 'BFP Sizes',
                'permissions': (('browse_bpsize', 'Can browse BP Size'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BPType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bp_type', models.CharField(max_length=10, verbose_name='BFP Type')),
            ],
            options={
                'verbose_name': 'BFP Type',
                'verbose_name_plural': 'BFP Types',
                'permissions': (('browse_bptype', 'Can browse BP Type'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('number', models.CharField(unique=True, max_length=15, verbose_name='Number')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('address1', models.CharField(max_length=100, verbose_name='Address 1')),
                ('address2', models.CharField(max_length=100, null=True, verbose_name='Address 2', blank=True)),
                ('apt', models.CharField(max_length=15, null=True, verbose_name='Customer Apt', blank=True)),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='State', choices=[(b'AL', b'Alabama'), (b'AK', b'Alaska'), (b'AZ', b'Arizona'), (b'AR', b'Arkansas'), (b'CA', b'California'), (b'CO', b'Colorado'), (b'CT', b'Connecticut'), (b'DE', b'Delaware'), (b'DC', b'District of Columbia'), (b'FL', b'Florida'), (b'GA', b'Georgia'), (b'HI', b'Hawaii'), (b'ID', b'Idaho'), (b'IL', b'Illinois'), (b'IN', b'Indiana'), (b'IA', b'Iowa'), (b'KS', b'Kansas'), (b'KY', b'Kentucky'), (b'LA', b'Louisiana'), (b'ME', b'Maine'), (b'MD', b'Maryland'), (b'MA', b'Massachusetts'), (b'MI', b'Michigan'), (b'MN', b'Minnesota'), (b'MS', b'Mississippi'), (b'MO', b'Missouri'), (b'MT', b'Montana'), (b'NE', b'Nebraska'), (b'NV', b'Nevada'), (b'NH', b'New Hampshire'), (b'NJ', b'New Jersey'), (b'NM', b'New Mexico'), (b'NY', b'New York'), (b'NC', b'North Carolina'), (b'ND', b'North Dakota'), (b'OH', b'Ohio'), (b'OK', b'Oklahoma'), (b'OR', b'Oregon'), (b'PA', b'Pennsylvania'), (b'RI', b'Rhode Island'), (b'SC', b'South Carolina'), (b'SD', b'South Dakota'), (b'TN', b'Tennessee'), (b'TX', b'Texas'), (b'UT', b'Utah'), (b'VT', b'Vermont'), (b'VA', b'Virginia'), (b'WA', b'Washington'), (b'WV', b'West Virginia'), (b'WI', b'Wisconsin'), (b'WY', b'Wyoming')])),
                ('zip', models.CharField(max_length=10, null=True, verbose_name='ZIP', blank=True)),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Phone', blank=True)),
                ('fax', models.CharField(max_length=15, null=True, verbose_name='Fax', blank=True)),
                ('email', models.EmailField(max_length=15, null=True, verbose_name='Email', blank=True)),
                ('notes', models.TextField(max_length=255, null=True, verbose_name='Notes', blank=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'permissions': (('browse_customer', 'Can browse Customer'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CustomerCode',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('customer_code', models.CharField(max_length=20, verbose_name='Customer Code')),
            ],
            options={
                'verbose_name': 'Customer Code',
                'verbose_name_plural': 'Customer Codes',
                'permissions': (('browse_customercode', 'Can browse Customer Code'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('address', models.CharField(max_length=50, null=True, verbose_name='Address', blank=True)),
                ('city', models.CharField(max_length=30, null=True, verbose_name='City', blank=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='State', choices=[(b'AL', b'Alabama'), (b'AK', b'Alaska'), (b'AZ', b'Arizona'), (b'AR', b'Arkansas'), (b'CA', b'California'), (b'CO', b'Colorado'), (b'CT', b'Connecticut'), (b'DE', b'Delaware'), (b'DC', b'District of Columbia'), (b'FL', b'Florida'), (b'GA', b'Georgia'), (b'HI', b'Hawaii'), (b'ID', b'Idaho'), (b'IL', b'Illinois'), (b'IN', b'Indiana'), (b'IA', b'Iowa'), (b'KS', b'Kansas'), (b'KY', b'Kentucky'), (b'LA', b'Louisiana'), (b'ME', b'Maine'), (b'MD', b'Maryland'), (b'MA', b'Massachusetts'), (b'MI', b'Michigan'), (b'MN', b'Minnesota'), (b'MS', b'Mississippi'), (b'MO', b'Missouri'), (b'MT', b'Montana'), (b'NE', b'Nebraska'), (b'NV', b'Nevada'), (b'NH', b'New Hampshire'), (b'NJ', b'New Jersey'), (b'NM', b'New Mexico'), (b'NY', b'New York'), (b'NC', b'North Carolina'), (b'ND', b'North Dakota'), (b'OH', b'Ohio'), (b'OK', b'Oklahoma'), (b'OR', b'Oregon'), (b'PA', b'Pennsylvania'), (b'RI', b'Rhode Island'), (b'SC', b'South Carolina'), (b'SD', b'South Dakota'), (b'TN', b'Tennessee'), (b'TX', b'Texas'), (b'UT', b'Utah'), (b'VT', b'Vermont'), (b'VA', b'Virginia'), (b'WA', b'Washington'), (b'WV', b'West Virginia'), (b'WI', b'Wisconsin'), (b'WY', b'Wyoming')])),
                ('zip', models.CharField(max_length=10, null=True, verbose_name='ZIP', blank=True)),
                ('phone1', models.CharField(max_length=20, null=True, verbose_name='Phone 1', blank=True)),
                ('phone2', models.CharField(max_length=20, null=True, verbose_name='Phone 2', blank=True)),
                ('fax', models.CharField(max_length=20, null=True, verbose_name='Fax', blank=True)),
                ('certificate', models.CharField(help_text='May be specified for testers', max_length=30, null=True, verbose_name='Cert. Number', blank=True)),
                ('company', models.CharField(max_length=30, null=True, verbose_name='Company', blank=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'permissions': (('browse_user', 'Can browse Users'), ('access_to_adminpanel', 'Can log into Admin Panel'), ('access_to_all_users', 'Has access to all Users'), ('access_to_pws_users', "Has access to PWS's Users")),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FloorsCount',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('floors_count', models.CharField(max_length=10, verbose_name='Floors Count')),
            ],
            options={
                'verbose_name': 'Floors Count',
                'verbose_name_plural': 'Floors Count',
                'permissions': (('browse_floorscount', 'Can browse Floors Count'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('location1', models.CharField(max_length=70, null=True, verbose_name='Location 1', blank=True)),
                ('location2', models.CharField(max_length=70, null=True, verbose_name='Location 2', blank=True)),
                ('installed_properly', models.BooleanField(default=False, verbose_name='Installed Properly', choices=[(True, b'Yes'), (False, b'No')])),
                ('installer', models.CharField(max_length=30, null=True, verbose_name='Installer', blank=True)),
                ('install_date', models.DateField(null=True, verbose_name='Install Date', blank=True)),
                ('replace_date', models.DateField(null=True, verbose_name='Replace Date', blank=True)),
                ('model_no', models.CharField(max_length=15, null=True, verbose_name='BP Model No.', blank=True)),
                ('serial_no', models.CharField(max_length=15, null=True, verbose_name='BP Serial No.', blank=True)),
                ('due_install_test_date', models.DateField(null=True, verbose_name='Due Install/Test Date', blank=True)),
                ('notes', models.TextField(max_length=255, null=True, verbose_name='Notes', blank=True)),
                ('assembly_location', models.ForeignKey(related_name='hazards', verbose_name='Assembly Location', blank=True, to='webapp.AssemblyLocation', null=True)),
                ('assembly_status', models.ForeignKey(related_name='hazards', verbose_name='Assembly Status', blank=True, to='webapp.AssemblyStatus', null=True)),
                ('bp_size', models.ForeignKey(related_name='hazards', verbose_name='BP Size', blank=True, to='webapp.BPSize', null=True)),
                ('bp_type_present', models.ForeignKey(related_name='hazards_p', verbose_name='BP Type Present', blank=True, to='webapp.BPType', null=True)),
                ('bp_type_required', models.ForeignKey(related_name='hazards_r', verbose_name='BP Type Required', blank=True, to='webapp.BPType', null=True)),
            ],
            options={
                'verbose_name': 'Hazard',
                'verbose_name_plural': 'Hazards',
                'permissions': (('browse_hazard', 'Can browse Hazard'), ('access_to_all_hazards', 'Has access to all Hazards'), ('access_to_pws_hazards', "Has access to PWS's Hazards"), ('access_to_own_hazards', 'Has access to own Hazards'), ('access_to_site_hazards', "Has access to Site's Hazards"), ('change_all_info_about_hazard', 'Can change all information about Hazard')),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HazardType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('hazard_type', models.CharField(max_length=50, verbose_name='Hazard Type')),
            ],
            options={
                'verbose_name': 'Hazard Type',
                'verbose_name_plural': 'Hazard Types',
                'permissions': (('browse_hazardtype', 'Can browse Hazard Type'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ICPointType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ic_point', models.CharField(max_length=20, verbose_name='Interconnection Point')),
            ],
            options={
                'verbose_name': 'Interconnection Point Type',
                'verbose_name_plural': 'Interconnection Point Types',
                'permissions': (('browse_icpointtype', 'Can browse Interconnection Point Type'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Assigned Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(max_length=255, null=True, verbose_name='Notes', blank=True)),
                ('assigned_by', models.ForeignKey(related_name='inspects_assigned', verbose_name='Assigned By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('assigned_to', models.ForeignKey(related_name='inspections', verbose_name='Assigned To', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'permissions': (('browse_inspection', 'Can browse Inspection'), ('access_to_all_inspections', 'Has access to all Inspections'), ('access_to_pws_inspections', "Has access to PWS's Inspections")),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Send Date')),
                ('hazard', models.ForeignKey(related_name='letters', verbose_name='Hazard', blank=True, to='webapp.Hazard', null=True)),
            ],
            options={
                'verbose_name': 'Letter',
                'verbose_name_plural': 'Letters',
                'permissions': (('browse_letter', 'Can browse Letter'), ('send_letter', 'Can send Letter')),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LetterType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('letter_type', models.CharField(max_length=20, verbose_name='Letter Type')),
                ('template', models.TextField(max_length=2000, null=True, verbose_name='Letter Template', blank=True)),
            ],
            options={
                'verbose_name': 'Letter Type',
                'verbose_name_plural': 'Letter Types',
                'permissions': (('browse_lettertype', 'Can browse Letter Type'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(max_length=255, null=True, verbose_name='Notes', blank=True)),
                ('given_by', models.ForeignKey(related_name='licences_given', verbose_name='Given By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('given_to', models.ForeignKey(related_name='licences', verbose_name='Given To', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
                'permissions': (('browse_licence', 'Can browse Licence'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('orientation', models.CharField(max_length=15, verbose_name='Orientation')),
            ],
            options={
                'verbose_name': 'Orientation Type',
                'verbose_name_plural': 'Orientation Types',
                'permissions': (('browse_orientation', 'Can browse Orientation Type'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PWS',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('number', models.CharField(max_length=15, verbose_name='Number')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='City', blank=True)),
                ('office_address', models.CharField(max_length=50, null=True, verbose_name='Office Address', blank=True)),
                ('notes', models.TextField(max_length=255, null=True, verbose_name='Notes', blank=True)),
            ],
            options={
                'verbose_name': 'Public Water System',
                'verbose_name_plural': 'Public Water Systems',
                'permissions': (('browse_pws', 'Can browse Public Water System'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('service_type', models.CharField(max_length=20, verbose_name='Service Type')),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
                'permissions': (('browse_servicetype', 'Can browse Service Type'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('connect_date', models.DateField(null=True, verbose_name='Connect Date', blank=True)),
                ('address1', models.CharField(max_length=100, verbose_name='Address 1')),
                ('address2', models.CharField(max_length=100, null=True, verbose_name='Address 2', blank=True)),
                ('apt', models.CharField(max_length=15, null=True, verbose_name='Apt', blank=True)),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='State', choices=[(b'AL', b'Alabama'), (b'AK', b'Alaska'), (b'AZ', b'Arizona'), (b'AR', b'Arkansas'), (b'CA', b'California'), (b'CO', b'Colorado'), (b'CT', b'Connecticut'), (b'DE', b'Delaware'), (b'DC', b'District of Columbia'), (b'FL', b'Florida'), (b'GA', b'Georgia'), (b'HI', b'Hawaii'), (b'ID', b'Idaho'), (b'IL', b'Illinois'), (b'IN', b'Indiana'), (b'IA', b'Iowa'), (b'KS', b'Kansas'), (b'KY', b'Kentucky'), (b'LA', b'Louisiana'), (b'ME', b'Maine'), (b'MD', b'Maryland'), (b'MA', b'Massachusetts'), (b'MI', b'Michigan'), (b'MN', b'Minnesota'), (b'MS', b'Mississippi'), (b'MO', b'Missouri'), (b'MT', b'Montana'), (b'NE', b'Nebraska'), (b'NV', b'Nevada'), (b'NH', b'New Hampshire'), (b'NJ', b'New Jersey'), (b'NM', b'New Mexico'), (b'NY', b'New York'), (b'NC', b'North Carolina'), (b'ND', b'North Dakota'), (b'OH', b'Ohio'), (b'OK', b'Oklahoma'), (b'OR', b'Oregon'), (b'PA', b'Pennsylvania'), (b'RI', b'Rhode Island'), (b'SC', b'South Carolina'), (b'SD', b'South Dakota'), (b'TN', b'Tennessee'), (b'TX', b'Texas'), (b'UT', b'Utah'), (b'VT', b'Vermont'), (b'VA', b'Virginia'), (b'WA', b'Washington'), (b'WV', b'West Virginia'), (b'WI', b'Wisconsin'), (b'WY', b'Wyoming')])),
                ('zip', models.CharField(max_length=10, null=True, verbose_name='ZIP', blank=True)),
                ('meter_number', models.CharField(max_length=20, null=True, verbose_name='Meter Number', blank=True)),
                ('meter_size', models.CharField(max_length=15, null=True, verbose_name='Meter Size', blank=True)),
                ('meter_reading', models.FloatField(null=True, verbose_name='Meter Reading', blank=True)),
                ('route', models.CharField(max_length=20, null=True, verbose_name='Seq. Route', blank=True)),
                ('potable_present', models.BooleanField(default=False, verbose_name='Potable Present', choices=[(True, b'Yes'), (False, b'No')])),
                ('fire_present', models.BooleanField(default=False, verbose_name='Fire Present', choices=[(True, b'Yes'), (False, b'No')])),
                ('irrigation_present', models.BooleanField(default=False, verbose_name='Irrigation Present', choices=[(True, b'Yes'), (False, b'No')])),
                ('is_due_install', models.BooleanField(default=False, verbose_name='Is Due Install', choices=[(True, b'Yes'), (False, b'No')])),
                ('is_backflow', models.BooleanField(default=False, verbose_name='Is Backflow Present', choices=[(True, b'Yes'), (False, b'No')])),
                ('next_survey_date', models.DateField(null=True, verbose_name='Next Survey Date', blank=True)),
                ('notes', models.TextField(max_length=255, null=True, verbose_name='Notes', blank=True)),
                ('last_survey_date', models.DateField(null=True, verbose_name='Last survey date', blank=True)),
                ('customer', models.ForeignKey(related_name='sites', verbose_name='Customer', to='webapp.Customer')),
                ('floors', models.ForeignKey(related_name='sites', verbose_name='Building Height', blank=True, to='webapp.FloorsCount', null=True)),
                ('interconnection_point', models.ForeignKey(related_name='sites', verbose_name='Interconnection Point', blank=True, to='webapp.ICPointType', null=True)),
                ('pws', models.ForeignKey(related_name='sites', verbose_name='PWS', to='webapp.PWS')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'permissions': (('browse_site', 'Can browse Site'), ('access_to_all_sites', 'Has access to all Sites'), ('access_to_pws_sites', "Has access to PWS's Sites"), ('access_to_survey_sites', 'Has access to Sites that he inspects'), ('access_to_test_sites', 'Has access to Sites that he tests'), ('access_to_import', 'Can import Sites from Excel file'), ('assign_surveyor', 'Can assign Surveyor to Site'), ('assign_tester', 'Can assign Tester to Site'), ('commit_site', 'Can commit Site'), ('access_to_batch_update', 'Has access to batch update')),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SiteStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('site_status', models.CharField(max_length=15, verbose_name='Site Status')),
            ],
            options={
                'verbose_name': 'Site Status',
                'verbose_name_plural': 'Site Status',
                'permissions': (('browse_sitestatus', 'Can browse Site Status'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('site_type', models.CharField(max_length=50, verbose_name='Site Type')),
            ],
            options={
                'verbose_name': 'Site Type',
                'verbose_name_plural': 'Site Types',
                'permissions': (('browse_sitetype', 'Can browse Site Type'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SiteUse',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('site_use', models.CharField(max_length=30, verbose_name='Site Use')),
            ],
            options={
                'verbose_name': 'Site Use',
                'verbose_name_plural': 'Site Use Types',
                'permissions': (('browse_siteuse', 'Can browse Site Use'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('source_type', models.CharField(max_length=50, verbose_name='Source Type')),
            ],
            options={
                'verbose_name': 'Source Type',
                'verbose_name_plural': 'Source Types',
                'permissions': (('browse_sourcetype', 'Can browse Source Type'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('special', models.CharField(max_length=5, verbose_name='Special')),
            ],
            options={
                'verbose_name': 'Special',
                'verbose_name_plural': 'Special',
                'permissions': (('browse_special', 'Can browse Special'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='StaticText',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('text', models.TextField(null=True, verbose_name='Text', blank=True)),
                ('group', models.ForeignKey(related_name='static_texts', verbose_name='Group', blank=True, to='auth.Group', null=True)),
            ],
            options={
                'verbose_name': 'Static Text',
                'verbose_name_plural': 'Static Text',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('survey_date', models.DateField(verbose_name='Survey Date')),
                ('metered', models.BooleanField(default=False, verbose_name='Metered', choices=[(True, b'Yes'), (False, b'No')])),
                ('pump_present', models.BooleanField(default=False, verbose_name='Pump Present', choices=[(True, b'Yes'), (False, b'No')])),
                ('additives_present', models.BooleanField(default=False, verbose_name='Additives Present', choices=[(True, b'Yes'), (False, b'No')])),
                ('cc_present', models.BooleanField(default=False, verbose_name='CC Present', choices=[(True, b'Yes'), (False, b'No')])),
                ('protected', models.BooleanField(default=False, verbose_name='Is Protected', choices=[(True, b'Yes'), (False, b'No')])),
                ('aux_water', models.BooleanField(default=False, verbose_name='Auxiliary Water', choices=[(True, b'Yes'), (False, b'No')])),
                ('detector_manufacturer', models.CharField(max_length=20, null=True, verbose_name='Detector Manufacturer', blank=True)),
                ('detector_model', models.CharField(max_length=20, null=True, verbose_name='Detector Model', blank=True)),
                ('detector_serial_no', models.CharField(max_length=20, null=True, verbose_name='Detector Serial No.', blank=True)),
                ('notes', models.TextField(max_length=255, null=True, verbose_name='Notes', blank=True)),
                ('service_type', models.ForeignKey(related_name='surveys', verbose_name='Service Type', to='webapp.ServiceType')),
                ('site', models.ForeignKey(related_name='surveys', verbose_name='Site', to='webapp.Site')),
                ('special', models.ForeignKey(related_name='surveys', verbose_name='Special', blank=True, to='webapp.Special', null=True)),
            ],
            options={
                'get_latest_by': 'survey_date',
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'permissions': (('browse_survey', 'Can browse Survey'), ('access_to_all_surveys', 'Has access to all Surveys'), ('access_to_pws_surveys', "Has access to PWS's Surveys"), ('access_to_own_surveys', 'Has access to own Surveys'), ('add_many_surveys_per_site', 'Can add many Surveys per Site')),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SurveyType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('survey_type', models.CharField(max_length=20, verbose_name='Survey Type')),
            ],
            options={
                'verbose_name': 'Survey Type',
                'verbose_name_plural': 'Survey Types',
                'permissions': (('browse_surveytype', 'Can browse Survey Type'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('test_serial_number', models.CharField(max_length=20, verbose_name='Test Serial No.')),
                ('last_calibration_date', models.DateField(verbose_name='Last Calibration Date')),
                ('test_date', models.DateField(auto_now_add=True, verbose_name='Test Date')),
                ('next_test_date', models.DateField(null=True, verbose_name='Next Test Date', blank=True)),
                ('cv1_leaked', models.BooleanField(default=False, verbose_name='CV1 Leaked', choices=[(True, b'Leaked'), (False, b'Closed')])),
                ('cv1_gauge_pressure', models.FloatField(null=True, verbose_name='CV1 Gauge Pressure', blank=True)),
                ('cv1_maintenance', models.BooleanField(default=False, verbose_name='CV1 Maintenance', choices=[(True, b'Yes'), (False, b'No')])),
                ('cv1_maintenance_pressure', models.FloatField(null=True, verbose_name='CV1 Maintenance Pressure', blank=True)),
                ('cv2_leaked', models.BooleanField(default=False, verbose_name='CV2 Leaked', choices=[(True, b'Leaked'), (False, b'Closed')])),
                ('cv2_gauge_pressure', models.FloatField(null=True, verbose_name='CV2 Gauge Pressure', blank=True)),
                ('cv2_maintenance', models.BooleanField(default=False, verbose_name='CV2 Maintenance', choices=[(True, b'Yes'), (False, b'No')])),
                ('cv2_maintenance_pressure', models.FloatField(null=True, verbose_name='CV2 Maintenance Pressure', blank=True)),
                ('rv_opened', models.BooleanField(default=False, verbose_name='RV Opened', choices=[(True, b'Opened'), (False, b'Closed')])),
                ('rv_psi1', models.FloatField(null=True, verbose_name='RV Pressure 1', blank=True)),
                ('rv_psi2', models.FloatField(null=True, verbose_name='RV Pressure 2', blank=True)),
                ('rv_maintenance', models.BooleanField(default=False, verbose_name='RV Maintenance', choices=[(True, b'Yes'), (False, b'No')])),
                ('outlet_sov_leaked', models.BooleanField(default=False, verbose_name='Outlet SOV Leaked', choices=[(True, b'Leaked'), (False, b'Closed')])),
                ('pvb_opened', models.BooleanField(default=False, verbose_name='PVB Opened', choices=[(True, b'Opened'), (False, b'Closed')])),
                ('pvb_open_pressure', models.FloatField(null=True, verbose_name='PVB Open Pressure', blank=True)),
                ('cv_leaked', models.BooleanField(default=False, verbose_name='CV Leaked', choices=[(True, b'Leaked'), (False, b'Closed')])),
                ('cv_held_pressure', models.FloatField(null=True, verbose_name='CV Held Pressure', blank=True)),
                ('cv_maintenance', models.BooleanField(default=False, verbose_name='CV Maintenance', choices=[(True, b'Yes'), (False, b'No')])),
                ('air_inlet_psi', models.FloatField(null=True, verbose_name='Air Inlet PSI', blank=True)),
                ('cv_psi', models.FloatField(null=True, verbose_name='CV PSI', blank=True)),
                ('test_result', models.BooleanField(default=False, verbose_name='Test Result', choices=[(True, b'Passed'), (False, b'Failed')])),
                ('notes', models.TextField(max_length=255, null=True, verbose_name='Notes', blank=True)),
                ('bp_device', models.ForeignKey(related_name='tests', verbose_name='BP Device', to='webapp.Hazard')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'permissions': (('browse_test', 'Can browse Test'), ('access_to_all_tests', 'Has access to all Tests'), ('access_to_pws_tests', "Has access to PWS's Tests"), ('access_to_own_tests', 'Has access to own Tests'), ('add_many_tests_per_hazard', 'Can add many Tests per Hazard')),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TestManufacturer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('test_manufacturer', models.CharField(max_length=20, verbose_name='Test Manufacturer')),
            ],
            options={
                'verbose_name': 'Test Manufacturer',
                'verbose_name_plural': 'Test Manufacturers',
                'permissions': (('browse_testmanufacturer', 'Can browse Test Manufacturer'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TestPermission',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('given_date', models.DateField(auto_now_add=True, verbose_name='Given Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(max_length=255, null=True, verbose_name='Notes', blank=True)),
                ('given_by', models.ForeignKey(related_name='test_perms_given', verbose_name='Given By', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('given_to', models.ForeignKey(related_name='test_perms_granted', verbose_name='Given To', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(related_name='test_perms', verbose_name='Site', to='webapp.Site')),
            ],
            options={
                'verbose_name': 'Test Permission',
                'verbose_name_plural': 'Test Permissions',
                'permissions': (('browse_testpermission', 'Can browse Test Permission'), ('access_to_all_testpermissions', 'Has access to all Test Permissions'), ('access_to_pws_testpermissions', "Has access to PWS's Test Permissions")),
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='test',
            name='test_manufacturer',
            field=models.ForeignKey(related_name='tests', verbose_name='Test Manufacturer', to='webapp.TestManufacturer'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='test',
            name='tester',
            field=models.ForeignKey(related_name='tests', verbose_name='Tester', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.ForeignKey(related_name='surveys', verbose_name='Survey Type', blank=True, to='webapp.SurveyType', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='survey',
            name='surveyor',
            field=models.ForeignKey(related_name='surveys', verbose_name='Surveyor', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.ForeignKey(related_name='sites', verbose_name='Site Type', blank=True, to='webapp.SiteType', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='site',
            name='site_use',
            field=models.ForeignKey(related_name='sites', verbose_name='Site Use', blank=True, to='webapp.SiteUse', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.ForeignKey(related_name='sites', verbose_name='Status', blank=True, to='webapp.SiteStatus', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pws',
            name='water_source',
            field=models.ForeignKey(related_name='pws', verbose_name='Water Source', blank=True, to='webapp.SourceType', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='letter',
            name='letter_type',
            field=models.ForeignKey(related_name='letters', verbose_name='Letter Type', to='webapp.LetterType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='letter',
            name='site',
            field=models.ForeignKey(related_name='letters', verbose_name='Site', blank=True, to='webapp.Site', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='letter',
            name='user',
            field=models.ForeignKey(related_name='letters', verbose_name='Sender', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='inspection',
            name='site',
            field=models.ForeignKey(related_name='inspections', verbose_name='Site', to='webapp.Site'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='hazard',
            name='hazard_type',
            field=models.ForeignKey(related_name='hazards', verbose_name='Hazard Type', to='webapp.HazardType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='hazard',
            name='manufacturer',
            field=models.ForeignKey(related_name='hazards', verbose_name='BP Manufacturer', blank=True, to='webapp.BPManufacturer', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='hazard',
            name='orientation',
            field=models.ForeignKey(related_name='hazards', verbose_name='orientation', blank=True, to='webapp.Orientation', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='hazard',
            name='survey',
            field=models.ForeignKey(related_name='hazards', verbose_name='Survey', to='webapp.Survey'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='employee',
            name='pws',
            field=models.ForeignKey(related_name='employees', blank=True, to='webapp.PWS', help_text='Should be specified for remote administrators to grant them data access', null=True, verbose_name='PWS'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.ForeignKey(related_name='customers', verbose_name='Customer Code', to='webapp.CustomerCode'),
            preserve_default=True,
        ),
    ]
